"""Phase 13 -- evidence packages built FROM EXISTING results.

Nothing here computes an analysis. This module reads the result objects that
Phases 6-12 already produce and states, in serializable form, what was measured
and how the answer was reached. If a fact is not in the result, it is reported
as `"unavailable"` -- it is never inferred.

The explanation text is generated by templates with no language model, no
branching on data values beyond the four outcome classes (matches / zero
matches / partial unknown / all unknown), and no wording that turns a
measurement into a cause.

The boundary sentence is imported from `analyses.multi_condition.CAVEAT`. It is
deliberately NOT copied: one constant, one wording, three places that show it.
"""

from __future__ import annotations

import os
from typing import Any, Dict, List, Optional, Tuple

from core.evidence import (
    UNKNOWN_ALL,
    UNKNOWN_NONE,
    UNKNOWN_NOT_APPLICABLE,
    UNKNOWN_PARTIAL,
    UNAVAILABLE,
    EvidencePackage,
    EvidenceRecord,
    Lineage,
    counts_of,
    unknown_handling_for,
)

from .multi_condition import CAVEAT

# --------------------------------------------------------------------------- #
# small readers -- every one of them tolerates a missing field
# --------------------------------------------------------------------------- #


def _text(value: Any, default: str = UNAVAILABLE) -> str:
    text = str(value).strip() if value is not None else ""
    return text or default


def _as_dict(value: Any) -> Dict[str, Any]:
    return dict(value) if isinstance(value, dict) else {}


def _scene_label(path: Any) -> str:
    """A scene name, shortened to a file name only when it is a path."""
    text = _text(path, "")
    if not text:
        return UNAVAILABLE
    return os.path.basename(text) if ("/" in text or "\\" in text) else text


def _grid_of(result: Any) -> Dict[str, Any]:
    """The grid a result was computed on, from whichever field carries it."""
    grid = getattr(result, "grid", None)
    if isinstance(grid, dict) and grid:
        return _as_dict(grid)
    if grid is not None and hasattr(grid, "to_dict"):
        try:
            return _as_dict(grid.to_dict())
        except Exception:
            return {}
    return {}


def _cell_area(grid: Dict[str, Any]) -> float:
    """m² per cell, from the transform when the grid does not state it."""
    area = grid.get("cell_area_m2")
    if area:
        return float(area)
    transform = tuple(grid.get("transform") or ())
    if len(transform) >= 6:
        return abs(float(transform[0]) * float(transform[4]))
    resolution = grid.get("resolution_m")
    return float(resolution) ** 2 if resolution else 0.0


def _counts_from(entry: Dict[str, Any]) -> Dict[str, int]:
    """Normalise the two counting conventions in use.

    Phase 12 writes `matched` / `non_matching` / `insufficient`; Phase 9's
    `GridMask.counts()` writes `matching_cells` / `non_matching_cells` /
    `insufficient_cells`. Both mean the same three states, so they are folded
    into one shape here and nowhere else.
    """
    nested = _as_dict(entry.get("counts"))
    pick = lambda *names: next(
        (v for n in names if (v := entry.get(n, nested.get(n))) is not None), 0)
    return counts_of(
        matched=pick("matched", "matching_cells", "true"),
        non_matching=pick("non_matching", "non_matching_cells", "false"),
        insufficient=pick("insufficient", "insufficient_cells", "unknown"),
        total=pick("total", "valid_cells", "analysed"),
    )


def _dates_of(result: Any) -> Tuple[str, ...]:
    dates = getattr(result, "source_dates", None)
    if isinstance(dates, dict) and dates:
        before, after = dates.get("before"), dates.get("after")
        if before or after:
            return tuple(_text(d) for d in (before, after) if d)
        if dates.get("scene_date"):
            return (_text(dates.get("scene_date")),)
    before = getattr(result, "before_date", None)
    after = getattr(result, "after_date", None)
    if before or after:
        return tuple(_text(d) for d in (before, after) if d)
    return ()


# --------------------------------------------------------------------------- #
# threshold provenance wording -- ONE place, reused by the UI
# --------------------------------------------------------------------------- #
def threshold_origin_text(spec: Optional[Dict[str, Any]]) -> str:
    """Where a threshold came from, in the words Phase 12 already uses."""
    spec = _as_dict(spec)
    if not spec:
        return UNAVAILABLE
    provenance = _text(spec.get("provenance"), "")
    detail = _text(spec.get("detail"), "")
    if provenance == "user_specified":
        return "from your query."
    if provenance == "config_convention":
        return (f"a display/query convention ({detail}) — enabled by you, and "
                f"not a scientific classification.")
    if provenance == "relative":
        return (f"relative to this area ({detail}) — a comparison within the "
                f"selected area, not an absolute class.")
    return detail or provenance or UNAVAILABLE


# --------------------------------------------------------------------------- #
# per-result builders
# --------------------------------------------------------------------------- #
def _composition_records(result: Any,
                         execution_provenance: Optional[Dict[str, Any]] = None
                         ) -> Tuple[List[EvidenceRecord], Optional[EvidenceRecord],
                                    List[EvidenceRecord], Dict[str, Any]]:
    """Phase 12: one record per condition, plus the combined mask and stats."""
    grid = _grid_of(result)
    cell = _cell_area(grid)
    parameters_by_name: Dict[str, Any] = {}
    limitations_by_name: Dict[str, Any] = {}
    for condition in getattr(result, "conditions", ()) or ():
        name = _text(getattr(condition, "name", ""), "")
        if not name:
            continue
        parameters_by_name[name] = _as_dict(getattr(condition, "parameters", {}))
        limitations_by_name[name] = tuple(
            getattr(condition, "limitations", ()) or ())

    dates = _dates_of(result)
    records: List[EvidenceRecord] = []
    for index, entry in enumerate(getattr(result, "condition_results", ()) or ()):
        entry = _as_dict(entry)
        kind = _text(entry.get("kind"), "condition")
        name = _text(entry.get("name"), f"condition_{index}")
        label = _text(entry.get("label"), name)
        counts = _counts_from(entry)
        params = _as_dict(parameters_by_name.get(name))
        provenance = _as_dict(entry.get("provenance"))
        dataset = _scene_label(provenance.get("dataset"))
        if kind == "spatial":
            dataset = _text(entry.get("source"), dataset)
            band = "land cover class"
        elif kind == "spectral":
            band = _text(entry.get("source"), "").split(":")[-1] or UNAVAILABLE
        elif kind == "temporal":
            # Phase 10 inside a composition: the source is an ENGINE and a pair
            # of dates, not a scene file.
            dataset = _text(provenance.get("source") or provenance.get("analysis"),
                            "Phase 10 NDVI change")
            band = "ndvi change class"
        else:
            band = _text(entry.get("source"), UNAVAILABLE)
        if kind == "temporal":
            before = _text(provenance.get("before_date"), "")
            after = _text(provenance.get("after_date"), "")
            record_dates: Tuple[str, ...] = tuple(d for d in (before, after) if d) or dates
        else:
            record_dates = dates if kind != "spatial" else ()
        records.append(EvidenceRecord(
            id=f"{kind}:{name}",
            kind=kind,
            label=("NOT " if entry.get("negated") else "") + label,
            source_analysis=_text(entry.get("source")),
            source_dataset=dataset,
            source_dates=record_dates,
            band_or_index=band,
            condition=name,
            parameters=params,
            operator=entry.get("operator"),
            threshold=entry.get("threshold"),
            threshold_provenance=_as_dict(entry.get("threshold_provenance")) or None,
            negated=bool(entry.get("negated", entry.get("negate", False))),
            grid=grid,
            counts=counts,
            area_m2=(counts["matched"] * cell) if cell else None,
            fraction=(counts["matched"] / counts["total"]) if counts["total"] else None,
            limitations=limitations_by_name.get(name, ()),
            provenance=provenance,
        ))

    combined_counts = counts_of(
        matched=getattr(result, "matched_cell_count", 0),
        non_matching=getattr(result, "non_matching_cell_count", 0),
        insufficient=getattr(result, "insufficient_cell_count", 0),
        total=getattr(result, "analysed_cell_count", 0)
        or (int(getattr(result, "matched_cell_count", 0) or 0)
            + int(getattr(result, "non_matching_cell_count", 0) or 0)
            + int(getattr(result, "insufficient_cell_count", 0) or 0)),
    )
    combined = EvidenceRecord(
        id="combined:all",
        kind="combined",
        label=_text(getattr(result, "expression", ""), "combined condition"),
        source_analysis="three-valued AND" if str(
            getattr(result, "operator", "and")) == "and" else "three-valued OR",
        source_dataset=", ".join(getattr(result, "source_analyses", ()) or ())
        or UNAVAILABLE,
        source_dates=dates,
        condition="combined",
        grid=grid,
        counts=combined_counts,
        area_m2=float(getattr(result, "matched_area_m2", 0.0) or 0.0),
        fraction=float(getattr(result, "matched_fraction", 0.0) or 0.0),
        runtime_ms=(getattr(result, "performance", {}) or {}).get("runtime_ms"),
    )

    statistics: List[EvidenceRecord] = []
    for index_name, summary in _as_dict(getattr(result, "index_summaries", {})).items():
        summary = _as_dict(summary)
        statistics.append(EvidenceRecord(
            id=f"statistics:{index_name}",
            kind="statistics",
            label=f"{str(index_name).upper()} measured over the matched cells",
            source_analysis=_text(summary.get("index"), "core.indices"),
            source_dataset=dataset,
            source_dates=dates,
            band_or_index=_text(index_name),
            condition="attached evidence",
            parameters={k: summary.get(k) for k in
                        ("mean", "median", "min", "max", "std", "valid_pixels")
                        if k in summary},
            grid=grid,
            counts=counts_of(total=summary.get("valid_pixels", 0)),
            provenance={"defined": bool(summary.get("defined")),
                        "computed_over": _text(summary.get("computed_over"), ""),
                        "reason": _text(summary.get("reason"), "")},
        ))
    return records, combined, statistics, {"cell_area_m2": cell}


def _spatial_records(result: Any,
                     execution_provenance: Optional[Dict[str, Any]] = None
                     ) -> Tuple[List[EvidenceRecord], Optional[EvidenceRecord],
                                List[EvidenceRecord], Dict[str, Any]]:
    """Phase 9: one record per spatial condition, plus the combined mask."""
    grid = _grid_of(result)
    cell = _cell_area(grid)
    records: List[EvidenceRecord] = []
    for index, entry in enumerate(getattr(result, "condition_results", ()) or ()):
        entry = _as_dict(entry)
        name = _text(entry.get("name"), f"condition_{index}")
        counts = _counts_from(entry)
        provenance = _as_dict(entry.get("provenance"))
        records.append(EvidenceRecord(
            id=f"spatial:{name}",
            kind="spatial",
            label=("NOT " if entry.get("negated") else "") + _text(entry.get("name"), name),
            source_analysis=_text(entry.get("source"), "worldcover"),
            source_dataset=_text(entry.get("source"), UNAVAILABLE),
            band_or_index="land cover class",
            condition=_text(entry.get("condition"), name),
            parameters={k: v for k, v in entry.items()
                        if k in ("classes", "distance_m", "min_class", "scenario",
                                 "class_label")},
            negated=bool(entry.get("negated", False)),
            grid=grid,
            counts=counts,
            area_m2=(counts["matched"] * cell) if cell else None,
            fraction=(counts["matched"] / counts["total"]) if counts["total"] else None,
            limitations=tuple(entry.get("limitations", ()) or ()),
            provenance=provenance,
        ))
    combined_counts = counts_of(
        matched=getattr(result, "matched_cell_count", 0),
        non_matching=getattr(result, "non_matching_cell_count", 0),
        insufficient=getattr(result, "insufficient_cell_count", 0),
        total=getattr(result, "analysed_cell_count", 0),
    )
    combined = EvidenceRecord(
        id="combined:all",
        kind="combined",
        label=_text(getattr(result, "expression", ""), "combined spatial condition"),
        source_analysis=_text(getattr(result, "operator", "and")).upper(),
        source_dataset="ESA WorldCover 2021 v200",
        condition="combined",
        grid=grid,
        counts=combined_counts,
        area_m2=float(getattr(result, "matched_area_m2", 0.0) or 0.0),
        fraction=float(getattr(result, "matched_fraction", 0.0) or 0.0),
        runtime_ms=(getattr(result, "performance", {}) or {}).get("runtime_ms"),
    )
    return records, combined, [], {"cell_area_m2": cell}


def _temporal_records(result: Any,
                      execution_provenance: Optional[Dict[str, Any]] = None
                      ) -> Tuple[List[EvidenceRecord], Optional[EvidenceRecord],
                                 List[EvidenceRecord], Dict[str, Any]]:
    """Phase 10: one record per change class, plus the delta statistics."""
    roi_cells = int(getattr(result, "roi_cell_count", 0) or 0)
    classes = (
        ("increase", int(getattr(result, "increased_count", 0) or 0)),
        ("stable", int(getattr(result, "stable_count", 0) or 0)),
        ("decrease", int(getattr(result, "decreased_count", 0) or 0)),
        ("insufficient", int(getattr(result, "insufficient_count", 0) or 0)),
    )
    dates = _dates_of(result)
    grid = {
        "crs": _text(getattr(result, "crs", ""), ""),
        "transform": [float(v) for v in tuple(getattr(result, "transform", ()) or ())],
        "resolution_m": getattr(result, "resolution", None),
    }
    records = [
        EvidenceRecord(
            id=f"temporal:{name}",
            kind="temporal",
            label=f"NDVI {name}",
            source_analysis="analyses.ndvi_change",
            source_dataset=(f"{_scene_label(getattr(result, 'before_scene', ''))} "
                            f"→ {_scene_label(getattr(result, 'after_scene', ''))}"),
            source_dates=dates,
            band_or_index="ndvi change class",
            condition=name,
            parameters={"change_class": name},
            grid={k: v for k, v in grid.items() if v not in (None, "", [])},
            counts=counts_of(matched=count, total=roi_cells) if name != "insufficient"
            else counts_of(insufficient=count, total=roi_cells),
            fraction=(count / roi_cells) if roi_cells else None,
            provenance={"thresholds": _as_dict(getattr(result, "thresholds", {})),
                        "alignment": _as_dict(getattr(result, "alignment", {}))},
        )
        for name, count in classes
    ]
    # Phase 10 classifies every cell; it does not FILTER anything. There is
    # therefore no combined "cells satisfying" record -- reporting one would
    # turn a classification into a false claim about a match.
    combined = EvidenceRecord(
        id="statistics:delta",
        kind="statistics",
        label="NDVI before → after",
        source_analysis="analyses.ndvi_change",
        source_dataset=(f"{_scene_label(getattr(result, 'before_scene', ''))} → "
                        f"{_scene_label(getattr(result, 'after_scene', ''))}"),
        source_dates=dates,
        band_or_index="ndvi",
        condition="delta statistics",
        parameters={k: getattr(result, k, None) for k in
                    ("before_mean", "after_mean", "delta_mean", "before_median",
                     "after_median", "delta_median", "delta_min", "delta_max",
                     "valid_pixel_count", "roi_cell_count")},
        grid=grid,
        counts=counts_of(
            matched=int(getattr(result, "valid_pixel_count", 0) or 0),
            insufficient=int(getattr(result, "insufficient_count", 0) or 0),
            total=roi_cells),
        provenance={"thresholds": _as_dict(getattr(result, "thresholds", {})),
                    "alignment": _as_dict(getattr(result, "alignment", {}))},
    )
    return records, None, [combined], {}


def _index_records(result: Any,
                   execution_provenance: Optional[Dict[str, Any]] = None
                   ) -> Tuple[List[EvidenceRecord], Optional[EvidenceRecord],
                              List[EvidenceRecord], Dict[str, Any]]:
    """Phase 6 / 11: statistics of one index inside the ROI."""
    stats = _as_dict(getattr(result, "stats", {}))
    index_name = _text(getattr(result, "index_name", ""), "ndvi")
    dataset = _scene_label((execution_provenance or {}).get("source"))
    record = EvidenceRecord(
        id=f"statistics:{index_name}",
        kind="statistics",
        label=f"{index_name.upper()} statistics over the selected area",
        source_analysis=f"core.indices:{index_name}",
        source_dataset=dataset,
        band_or_index=index_name,
        condition="roi statistics",
        parameters={**stats,
                    "pixels_inside_roi": getattr(result, "pixels_inside_roi", None),
                    "valid_pixels": getattr(result, "valid_pixels", None),
                    "invalid_pixels": getattr(result, "invalid_pixels", None),
                    "valid_fraction": getattr(result, "valid_fraction", None)},
        grid={"crs": _text(getattr(result, "crs", ""), ""),
              "transform": [float(v) for v in tuple(getattr(result, "transform", ()) or ())],
              "pixel_size_m": [getattr(result, "pixel_width", None),
                               getattr(result, "pixel_height", None)]},
        counts=counts_of(
            matched=int(getattr(result, "valid_pixels", 0) or 0),
            insufficient=int(getattr(result, "invalid_pixels", 0) or 0),
            total=int(getattr(result, "pixels_inside_roi", 0) or 0)),
        area_m2=float(getattr(result, "valid_area_m2", 0.0)
                      or getattr(result, "area_m2", 0.0) or 0.0),
        fraction=float(getattr(result, "valid_fraction", 0.0) or 0.0),
        provenance={"window": getattr(result, "window", None),
                    "all_touched": getattr(result, "all_touched", None)},
    )
    return [], None, [record], {}


def _generic_records(result: Any,
                     execution_provenance: Optional[Dict[str, Any]] = None
                     ) -> Tuple[List[EvidenceRecord], Optional[EvidenceRecord],
                                List[EvidenceRecord], Dict[str, Any]]:
    """Fallback: report what IS in the object rather than guessing at it."""
    grid = _grid_of(result)
    record = EvidenceRecord(
        id="statistics:result",
        kind="statistics",
        label=_text(getattr(result, "expression", ""), "analysis result"),
        source_analysis=_text(getattr(result, "source_analysis", ""),
                              type(result).__name__),
        grid=grid,
        counts=counts_of(
            matched=int(getattr(result, "matched_cell_count", 0) or 0),
            non_matching=int(getattr(result, "non_matching_cell_count", 0) or 0),
            insufficient=int(getattr(result, "insufficient_cell_count", 0) or 0),
            total=int(getattr(result, "analysed_cell_count", 0) or 0)),
        area_m2=float(getattr(result, "matched_area_m2", 0.0) or 0.0),
        runtime_ms=(getattr(result, "performance", {}) or {}).get("runtime_ms"),
        provenance=_as_dict(getattr(result, "provenance", {})),
    )
    combined = record if (record.counts["total"] or record.area_m2) else None
    return [], combined, ([] if combined else [record]), {}


def _builders(result: Any):
    """Pick the builder that matches the result, without importing engines."""
    if hasattr(result, "condition_results") and hasattr(result, "combined_mask"):
        return _composition_records
    if hasattr(result, "result_mask") and hasattr(result, "condition_masks"):
        return _spatial_records
    if hasattr(result, "class_raster") and hasattr(result, "before_date"):
        return _temporal_records
    if hasattr(result, "stats") and hasattr(result, "valid_pixels"):
        return _index_records
    return _generic_records


# --------------------------------------------------------------------------- #
# the package
# --------------------------------------------------------------------------- #
def build_evidence(result: Any,
                   *,
                   intent: str = "",
                   query: str = "",
                   normalized_query: str = "",
                   status: str = "",
                   provenance: Optional[Dict[str, Any]] = None,
                   runtime_ms: Optional[float] = None) -> EvidencePackage:
    """Turn an existing result object into an auditable evidence package.

    The result is read, never modified, and never re-analysed.
    """
    builder = _builders(result)
    records, combined, statistics, extra = builder(result, provenance)
    # One spelling of a status, whether it came from the enum, from
    # `AnalysisExecution.to_dict()` or from the result object itself.
    status = _text(status).upper()
    grid = _grid_of(result)
    counts = combined.counts if combined is not None else counts_of()
    if not counts.get("total") and statistics:
        counts = statistics[0].counts

    sources: List[Dict[str, Any]] = []
    seen: set = set()
    # The combined mask is an operation, not a source: listing it would
    # suggest a dataset that does not exist.
    for record in list(records) + list(statistics):
        key = (record.source_analysis, record.source_dataset)
        if key in seen:
            continue
        seen.add(key)
        dataset = record.source_dataset
        sources.append({
            "analysis": record.source_analysis,
            # "x — x" reads as a fault; print one name when they match.
            "dataset": ("" if dataset == record.source_analysis else dataset),
            "dates": list(record.source_dates),
            "band_or_index": record.band_or_index,
        })

    limitations = tuple(getattr(result, "limitations", ()) or ())
    threshold_provenance = _as_dict(getattr(result, "threshold_provenance", {}))
    composed = any(r.kind in ("spatial", "spectral", "temporal") for r in records)

    package = EvidencePackage(
        query=_text(query, _text(getattr(result, "query", ""), "")),
        normalized_query=_text(
            normalized_query, _text(getattr(result, "normalized_query", ""), "")),
        intent=_text(intent, UNAVAILABLE),
        status=_text(status, _text(getattr(result, "status", ""), UNAVAILABLE)),
        expression=_text(getattr(result, "expression", ""), ""),
        records=tuple(records),
        combined=combined,
        statistics=tuple(statistics),
        sources=tuple(sources),
        grid=grid,
        alignment=_as_dict(getattr(result, "alignment", {})),
        threshold_provenance=threshold_provenance,
        analysed_cells=int(counts.get("matched", 0)) + int(counts.get("non_matching", 0)),
        matched_cells=int(counts.get("matched", 0)),
        non_matching_cells=int(counts.get("non_matching", 0)),
        unknown_cells=int(counts.get("insufficient", 0)),
        matched_area_m2=float(combined.area_m2 or 0.0) if combined else 0.0,
        unknown_handling=unknown_handling_for(counts),
        limitations=limitations,
        boundary=CAVEAT if composed else "",
        runtime_ms=runtime_ms if runtime_ms is not None
        else (getattr(result, "performance", {}) or {}).get("runtime_ms"),
        lineage=Lineage(
            query=_text(query, _text(getattr(result, "query", ""), "")),
            normalized_query=_text(
                normalized_query, _text(getattr(result, "normalized_query", ""), "")),
            intent=_text(intent, UNAVAILABLE),
            conditions=tuple(r.label for r in records),
            sources=tuple(getattr(result, "source_analyses", ()) or ())
            or tuple(s["analysis"] for s in sources),
            grid=grid,
            masks=tuple(r.id for r in records),
            combined=combined.label if combined else "",
            statistics=tuple(r.label for r in statistics),
            answer=_text(getattr(result, "message", ""), ""),
        ),
    )
    package.explanation.update(explain(package))
    return package


def evidence_from_execution(execution: Any) -> Optional[EvidencePackage]:
    """Build a package straight from an `AnalysisExecution`.

    A refused or unsupported query produced no measurement, so it gets no
    package at all: there is no evidence to describe, and inventing an empty
    one would read like a result of zero.
    """
    result = getattr(execution, "result", None)
    status = getattr(getattr(execution, "status", None), "value",
                     str(getattr(execution, "status", "") or ""))
    if result is None or str(status).upper() != "OK":
        return None
    intent = getattr(getattr(execution, "intent", None), "value",
                     str(getattr(execution, "intent", "") or ""))
    return build_evidence(
        result,
        intent=intent,
        query=_text(getattr(execution, "query", ""), ""),
        normalized_query=_text(getattr(execution, "normalized_query", ""), ""),
        status=getattr(getattr(execution, "status", None), "value",
                       str(getattr(execution, "status", "") or "")),
        provenance=_as_dict(getattr(execution, "provenance", {})),
    )


# --------------------------------------------------------------------------- #
# the deterministic explanation
# --------------------------------------------------------------------------- #
def explain(package: EvidencePackage) -> Dict[str, Any]:
    """Text blocks, generated from the package by templates. No model.

    The four outcome classes are distinguished on `analysed_cells`, never on
    `matched_cells` alone: "nothing could be measured" must never be printed as
    "nothing matched". A result that CLASSIFIES cells (Phase 10) is described
    as a classification, never as a filter that selected them.
    """
    counts = {"matched": package.matched_cells,
              "non_matching": package.non_matching_cells,
              "insufficient": package.unknown_cells,
              "total": package.analysed_cells + package.unknown_cells}
    handling = package.unknown_handling
    expression = package.expression or "the requested conditions"
    is_filter = package.combined is not None and bool(package.records)

    if is_filter and handling == UNKNOWN_ALL:
        found = "No cells could be evaluated with sufficient data."
    elif is_filter and package.matched_cells == 0 and handling in (
            UNKNOWN_NONE, UNKNOWN_PARTIAL):
        found = (f"No cells satisfy {expression}. Every measured cell was "
                 f"evaluated and did not match.")
    elif is_filter:
        found = (f"{package.matched_cells:,} cells satisfy {expression} over "
                 f"{package.analysed_cells:,} measured cells "
                 f"({package.unknown_cells:,} undecided).")
    else:
        found = _statistics_sentence(package)

    # ---- the undecided cells, always stated in their own sentence ---------- #
    if is_filter and handling == UNKNOWN_PARTIAL:
        unknown_note = (f"{package.matched_cells:,} cells matched; "
                        f"{package.unknown_cells:,} cells were undecided and "
                        f"were not counted as matches.")
    elif is_filter and handling == UNKNOWN_ALL:
        unknown_note = ("No cells could be evaluated with sufficient data. "
                        "That is not the same finding as \"no matches\".")
    elif is_filter and handling == UNKNOWN_NONE:
        unknown_note = ("Every measured cell was decided; no cells were left "
                        "undecided.")
    elif package.unknown_cells:
        unknown_note = (f"{package.unknown_cells:,} cells had no valid value "
                        f"and were excluded from the statistics.")
    elif package.statistics:
        unknown_note = "Every cell in the selection had a valid value."
    else:
        unknown_note = ""

    # ---- what was evaluated ------------------------------------------------ #
    evaluated: List[str] = []
    for record in package.records:
        line = f"{record.label} — from {record.source_analysis}"
        if record.threshold is not None:
            line += (f", {record.operator or ''} {record.threshold}"
                     f" ({threshold_origin_text(record.threshold_provenance)})")
        elif record.parameters:
            line += f", parameter {_parameter_text(record)}"
        if record.source_dataset and record.source_dataset != UNAVAILABLE:
            line += f", source {record.source_dataset}"
        evaluated.append(line.rstrip(".") + ".")

    # ---- how it was evaluated ---------------------------------------------- #
    grid_text = (f"{package.grid.get('width', UNAVAILABLE)} x "
                 f"{package.grid.get('height', UNAVAILABLE)} cells at "
                 f"{package.grid.get('resolution_m', UNAVAILABLE)} m"
                 if package.grid else UNAVAILABLE)
    if is_filter:
        operator = ("AND" if "AND" in str(package.combined.source_analysis).upper()
                    else "OR")
        joiner = ("every condition is TRUE" if operator == "AND"
                  else "at least one condition is TRUE")
        how = (f"The conditions were combined using three-valued {operator} "
               f"logic on a common grid ({grid_text}). A cell matches only when "
               f"{joiner}; a cell with missing data stays UNKNOWN and is never "
               f"counted as a non-match.")
    elif any(r.kind == "temporal" for r in package.records):
        how = ("NDVI was computed for each date on the shared grid and the "
               "difference was classified with the configured thresholds. "
               "Cells without a valid value in either date stay UNKNOWN and "
               "are never counted as change in either direction.")
    elif package.statistics:
        how = ("Statistics were computed over the cells inside the selected "
               "area, using the same validity mask the engine reports.")
    else:
        how = UNAVAILABLE

    return {
        "what_was_asked": package.normalized_query or package.query or UNAVAILABLE,
        "what_was_evaluated": evaluated,
        "what_was_found": found,
        "how_it_was_evaluated": how,
        "evidence_sources": [
            s["analysis"] + (f" — {s['dataset']}" if s.get("dataset") else "")
            + (f" ({', '.join(s['dates'])})" if s.get("dates") else "")
            for s in package.sources],
        "unknown_note": unknown_note,
        "unknown_handling": handling,
        "counts": counts,
        "limitations": list(package.limitations),
        "boundary": package.boundary,
    }


def _statistics_sentence(package: EvidencePackage) -> str:
    """One factual sentence about a statistics-only result."""
    if not package.statistics:
        # Not "no matches": nothing was measured at all.
        return ("Nothing was measured for this question, so there is no "
                "number to report.")
    record = package.statistics[0]
    params = record.parameters
    index = record.band_or_index.upper() or "index"
    valid = record.counts.get("total", 0)
    mean = params.get("mean")
    if mean is None:
        return (f"{index} was measured over {valid:,} valid cells inside the "
                f"selected area.")
    return (f"{index} over the selected area: mean {float(mean):.4f}, "
            f"median {float(params.get('median', 0) or 0):.4f}, "
            f"{record.counts.get('matched', 0):,} valid cells.")


def _parameter_text(record: EvidenceRecord) -> str:
    """The parameters of a condition, in the order a reader would expect."""
    params = record.parameters
    if "classes" in params:
        return ", ".join(str(c) for c in params["classes"])
    if "distance_m" in params:
        return f"{float(params['distance_m']):,.0f} m"
    if "class" in params:
        return str(params["class"])
    if "change_class" in params:
        return str(params["change_class"])
    if "min_class" in params:
        return str(params["min_class"])
    return ", ".join(f"{k}={v}" for k, v in list(params.items())[:3]) or UNAVAILABLE


# --------------------------------------------------------------------------- #
# rows for the "why this result" table
# --------------------------------------------------------------------------- #
def condition_rows(package: EvidencePackage) -> List[Dict[str, Any]]:
    """One row per condition: what it was, where it came from, what it did."""
    rows: List[Dict[str, Any]] = []
    for record in package.records:
        if record.kind == "spectral":
            parameter = (f"Threshold: {record.operator or ''} {record.threshold}"
                         if record.threshold is not None else UNAVAILABLE)
            origin = threshold_origin_text(record.threshold_provenance)
        elif record.kind == "temporal":
            parameter = f"Change class: {_parameter_text(record)}"
            origin = ("Before " + record.source_dates[0]
                      if len(record.source_dates) > 0 else UNAVAILABLE)
            if len(record.source_dates) > 1:
                origin += f" → After {record.source_dates[1]}"
            origin += " · Phase 10 NDVI change"
        else:
            parameter = ("Water class: 80 · " if "distance_m" in record.parameters
                         else "Class: ") + _parameter_text(record) \
                if record.parameters else UNAVAILABLE
            origin = record.source_dataset
        rows.append({
            "condition": record.label,
            "source": record.source_dataset,
            "analysis": record.source_analysis,
            "parameter": parameter,
            "origin": origin,
            "matched": record.matched,
            "non_matching": record.non_matching,
            "unknown": record.unknown,
        })
    return rows


def source_rows(package: EvidencePackage) -> List[Dict[str, str]]:
    """The datasets and scenes an answer came from."""
    rows: List[Dict[str, str]] = []
    for source in package.sources:
        rows.append({
            "analysis": _text(source.get("analysis")),
            "dataset": _text(source.get("dataset")),
            "dates": ", ".join(source.get("dates") or ()) or UNAVAILABLE,
            "band_or_index": _text(source.get("band_or_index"), ""),
        })
    return rows


def _plain_number(value: Any) -> str:
    """3460320.0 -> '3460320'; 10.0 -> '10'; no exponent, no trailing zeros."""
    try:
        number = float(value)
    except Exception:
        return _text(value)
    text = f"{number:.6f}".rstrip("0").rstrip(".")
    return text or "0"


def grid_rows(package: EvidencePackage) -> List[Tuple[str, str]]:
    """The reproducibility facts, in the order Step 7 lists them."""
    grid = package.grid or {}
    transform = tuple(grid.get("transform") or ())
    # A composition carries its per-source alignment blocks nested under the
    # source name ("temporal": {...}); the reproducibility row wants the one
    # that actually produced the grid.
    alignment = package.alignment or {}
    for key in ("temporal", "spectral", "spatial"):
        nested = _as_dict(alignment.get(key))
        if nested and ("method" in nested or "resampled" in nested):
            alignment = nested
            break
    resampled = bool(alignment.get("resampled"))
    rows = [
        ("Query", package.query or UNAVAILABLE),
        ("Normalized query", package.normalized_query or UNAVAILABLE),
        ("Intent", package.intent or UNAVAILABLE),
        ("Analysis dates", (", ".join(package.combined.source_dates)
                            if package.combined and package.combined.source_dates
                            else "not recorded for this result")),
        ("CRS", _text(grid.get("crs"))),
        ("Grid", (f"{grid.get('width', UNAVAILABLE)} x "
                  f"{grid.get('height', UNAVAILABLE)} cells") if grid else UNAVAILABLE),
        ("Resolution", (f"{grid.get('resolution_m'):g} m"
                        if grid.get("resolution_m") else UNAVAILABLE)),
        ("Transform", ", ".join(_plain_number(v) for v in transform)
         if transform else UNAVAILABLE),
        ("Alignment method", _text(alignment.get("method")
                                   or alignment.get("grid_source"))),
        ("Resampling", UNAVAILABLE if not alignment else
         ("none — computed on the native grid" if not resampled
          else _text(alignment.get("resampling")))),
        ("Analysed cells", f"{package.analysed_cells:,}"),
        ("Undecided cells", f"{package.unknown_cells:,}"),
        ("Matched area", f"{package.matched_area_km2:,.3f} km²"),
        ("Unknown handling", package.unknown_handling),
        ("Runtime", f"{package.runtime_ms:,.1f} ms" if package.runtime_ms
         is not None else UNAVAILABLE),
    ]
    for name, spec in (package.threshold_provenance or {}).items():
        rows.append((f"Threshold — {name}", threshold_origin_text(_as_dict(spec))))
    return rows


__all__ = [
    "build_evidence",
    "condition_rows",
    "evidence_from_entry",
    "evidence_from_execution",
    "explain",
    "grid_rows",
    "source_rows",
    "threshold_origin_text",
]


def evidence_from_entry(entry: Any) -> Optional[EvidencePackage]:
    """Build a package from one chat-history entry.

    The app stores `AnalysisExecution.to_dict()` plus the live result object;
    this is the bridge that keeps the app from re-implementing the contract.
    Refusals and unsupported queries have nothing to explain, so they are not
    given a package at all -- they never carry a result.
    """
    if not isinstance(entry, dict):
        return None
    if str(entry.get("status", "")).upper() != "OK" or entry.get("result") is None:
        return None
    provenance = _as_dict(entry.get("provenance"))
    return build_evidence(
        query=_text(entry.get("query"), ""),
        normalized_query=_text(entry.get("normalized_query"), ""),
        intent=entry.get("intent") or UNAVAILABLE,
        status=str(entry.get("status", "") or ""),
        result=entry.get("result"),
        provenance=provenance,
        runtime_ms=provenance.get("runtime_ms"),
    )
